### ISSUE TITLE
Removing time limits is not working

### ISSUE THREAD

**Issue by Pr3dat0rGam1ng** [Stigmatoz/web-activity-time-tracker#87]
I recently added a time limit for a website and now I can't remove it. It also changed the layout of the website completely.

**Comment by nilshah98** [comment]
- There is `X` near the `pencil` icon to delete limit for a website you already added. Please find image below -
<img width="854" alt="Screenshot 2023-01-18 at 11 20 43 PM" src="https://user-images.githubusercontent.com/22821480/213256911-556b7bd8-8741-44ac-b0ec-5477d5f8cbee.png">
- I don't think this is happening because of the extension, could you possible de-activate every other extension that you have , and try again just with `web-activity-time-tracker` extension active ?
- - You could also do it the other way, where you disable the `web-activity-time-tracker` and keep every other extension active to see if the issue is fixed, this will help you isolate which extension is causing it.

**Comment by nilshah98** [comment]
I have forked this repo, and added this fix. You can find the PR for the same at https://github.com/Stigmatoz/web-activity-time-tracker/pull/88

You can check [this](https://stackoverflow.com/a/16688027/8152977) for how to use an unpacked chrome extension.
